name: smart_city_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  onesignal_flutter: ^5.2.2
  go_router: ^14.2.1
  flutter_svg: ^2.0.10+1
  provider: ^6.0.0
  image_picker: ^1.1.2
  http: ^1.2.1
  flutter_local_notifications: ^17.2.1+2
  dio: ^5.5.0+1
  shared_preferences: ^2.0.6
  firebase_messaging: ^15.0.3
  google_maps_flutter: ^2.3.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - asset/image/